dist: trusty
language: node_js
node_js:
  - "10"
cache: npm
install:
  - npm install
  - npm install -D webpack-cli
script:
  - npx webpack -y
deploy:
  provider: s3
  skip_cleanup: true
  default_text_charset: utf-8
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dist
  bucket: "mrkfrmn.com"
  region: us-east-1