dist: trusty
language: node_js
node_js:
  - "10"
cache: npm
script:
  - npx webpack
deploy:
  provider: s3
  default_text_charset: utf-8
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  local_dir: dist
  bucket: "superdupercomplexbucketname"
  region: us-east-1