name: build
run-name: ${{ github.actor }} is building a new version of the site.
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-node@v3
       with:
         node-version: '10'
     - run: npm --prefix site install
     - run: npm --prefix site run convert
     - run: npm --prefix site run build
     - uses: actions/upload-artifact@v3
       with:
         name: dist
         path: ./site/dist
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - uses: actions/setup-python@v4
       with:
         python-version: '3.10'
     - run: pip install -r tool/requirements.txt
     - run: python3 tool/upload-to-s3.py
